### ISSUE TITLE
ipynb code can't run.

### ISSUE THREAD

**Issue by jinguman** [omarmohamed15/DLPGA#1]
Hello,

Thanks for sharing DLPGA tests code(VIT_PGA_Instance_Test.ipynb). 
But, I noticed that there is a missing when I executed the code. (convF1, Pathchs, PatchEncoder, mlp, transformer_units, etc... )
Can you upload the rest of code?

Thanks.

**Comment by omarmohamed15** [comment]
Many thanks for your interest in our code, we upload the missing file.
